### ISSUE TITLE
using pipes crashes minishell : "echo a | echo b" ,  "ls | echo b" ...

### ISSUE THREAD

**Issue by harou24** [harou24/Minishell#247] opened 2021-04-23 18:39 UTC

**Comment by s-t-a-n** [comment] 2021-04-24 13:22
I cannot reproduce this issue.

Running

    ./minishell -c 'echo a | echo b" , "ls | echo b'

yields the exact same result as

    bash -c 'echo a | echo b" , "ls | echo b'

same goes for running interactively.

Can you elaborate?

**Comment by harou24** [comment] 2021-04-24 15:30
![Screenshot_2021-04-24_17-29-55](https://user-images.githubusercontent.com/61208023/115964048-cf47ea80-a522-11eb-9bdf-9c4ef331823b.png)

**Comment by s-t-a-n** [comment] 2021-04-25 11:18
Could you upload the debug log? This just shows there is a problem, not what the problem is. You are sure your HEAD is @ ab89e54c0ad1bcb61cfacf2e0bd011c5ed523764 in develop? 

From the looks of it the output of the command 'ls' is interpreted by minishell as new commands. Thats weird. I cannot reproduce this, not on my laptop, Docker or OSx on Guacamole :o

**Comment by s-t-a-n** [comment] 2021-04-25 11:19
btw, you say it "crashes minishell" but I don't see it crashing?

**Comment by s-t-a-n** [comment] 2021-04-25 12:08
@harou24 I just added a PR, could you have a look whether it's fixed?

In absence of a log, I managed to replicate the bug in a bare docker container. It seems that on some systems the pipe get's dumped onto stdin when closing the pipe (without dupping it i presume), causing the get_next_line() call to interpret the commands output as input.

**Comment by harou24** [comment] 2021-04-25 12:11
yes it's good, it is working again !!

**Closed as completed** 2021-04-25 12:12 UTC
